# MLProject/conda.yaml
name: iris_ci_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip=23.3.2
  - scikit-learn=1.4.2  # Diperbaiki versinya
  - pandas=2.2.1
  - pip:
    - mlflow==2.11.3